### PR TITLE
Added support for api v2

### PR DESCRIPTION
**Pull request by Persiasty**
Fix for #3

### CODE REVIEW

**Comment by WilixLead** [comment]
I hope you test it before :)
I don't have my bracelete now, and I can try to build and upload to Google Play.

Thanks for helping!

**Comment by Persiasty** [comment]
It's work fine with my i5+ with fw 2.1.1.7
14247556_534736270049542_6858394_o

**Comment by ghost** [comment]
Could you provide building instructions or the apk for testing the working with my i5+ fw2?

Thanks!

**Comment by schneefux** [comment]
@Fubukimaru:

``` bash
curl -s https://gist.githubusercontent.com/schneefux/f300dc5adcc32a0290ca19bc64d5c72f/raw/43e00e04a6548521bdaef6730a62c7b7b501669a/build-in-debug-mode.patch | git apply -
npm install
./gradlew build
adb install -r ./Application/build/outputs/apk/Application-debug.apk
```

**Comment by ghost** [comment]
@schneefux  Thanks for your reply. I'm getting the following error:

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':Application'.
  
  > Could not resolve all dependencies for configuration ':Application:_debugCompile'.
  > Could not find com.google.android.gms:play-services:7.8.0.
  >  Searched in the following locations:
  >      https://jcenter.bintray.com/com/google/android/gms/play-services/7.8.0/play-services-7.8.0.pom
  >      https://jcenter.bintray.com/com/google/android/gms/play-services/7.8.0/play-services-7.8.0.jar
  >  Required by:
  >      iWownController:Application:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

https://jcenter.bintray.com/com/google/android/gms/play-services/7.8.0/play-services-7.8.0.jar
This link seem to be broken. Any replacements?

**Comment by sixman9** [comment]
As I've just purchased an IWon 5+, and am **not** interested in installing the Zeroner application (**excessive** permission list!), I have an extreme interest in getting this applicaton working.

I've pinpointed a source for the Google Play services version 7.8.0 JAR files, directly from Google, this can be unpackaged and added as a local library to your Gradle script, or installed into the local Maven repository (see CLI command, below). The URL of the play-services-7.8.0.jar-containing ZIP file is:

https://dl-ssl.google.com/android/repository/google_play_services_7895000_r26.zip (7.8.0 corresponds to revision 26)

A further list of such package ZIPs is available at:

http://stackoverflow.com/questions/20982533/how-to-download-older-google-play-services/26838281#26838281

Referencing the play service dependency
-----------------------------------------

com.google.android.gms:play-services:7.8.0


    #Adding the library locally with Maven (mvn) installed
    #See https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
    mvn install:install-file -Dfile=<path-to-file> -DgroupId=com.google.android.gms -DartifactId=play-services -Dversion=7.8.0 -Dpackaging=jar

or

    #Have Gradle depend on a local version, in some directory - see http://stackoverflow.com/a/20956456/304330
    dependencies {
        compile files('libs/play-services.jar')
    }


You *might* be able to use the latter technique, **and** check the JAR into the repository (addition of a 'libs' directory), although I don't necessarily advise that, given possible licensing issues.

Also, it should be possible to automate the ZIP's download and dependency resolution (extraction) using Gradle and the ['download' task][1] 

Hope this helps ;-)

[1]: https://github.com/michel-kraemer/gradle-download-task

**Pull request merged**
